In [74]:
import numpy as np
import math
person = "amit_fast_7"
file = "C:/Users/tanishqjasoria/Documents/Github/Rehab/gaitCycle-data/"+person+"/test_databack.txt"
#file = "C:\Users\tanishqjasoria\Documents\GitHub\Rehab\gaitCycle-data\_fast_7\test_databack.txt"

In [75]:
f = open(file)
lines = []
time = []
t1_temp=[]
t2_temp=[]
k1_temp=[]
k2_temp=[]
w_temp=[]
back_temp=[]
t1=[]
t2=[]
k1=[]
k2=[]
w=[]
back=[]
t1_old_theta=[0,0]
t2_old_theta=[0,0]
k1_old_theta=[0,0]
k2_old_theta=[0,0]
pitch_roll=[]
PI = 3.14159265

In [76]:
for line in f:
    lines.append(line) 

In [77]:
for i in range(5):
    lines.pop(0)
    lines.pop()

In [78]:
for elem in lines:
    if elem == '\n':
        lines.remove('\n')

In [79]:
for x in lines:
    a = x.split("=")
    t1_temp=[]
    t2_temp=[]
    k1_temp=[]
    k2_temp=[]
    w_temp=[]
    back_temp=[]
    t1_temp.append(float(a[1].strip().split(" ")[0]))
    t1_temp.append(float(a[2].strip().split(" ")[0]))
    t1_temp.append(float(a[3].strip().split(" ")[0]))
    t1_temp.append((float(a[4].strip().split(" ")[0]))/131)
    t1_temp.append(-(float(a[5].strip().split(" ")[0]))/131)
    t1_temp.append((float(a[6].strip().split(" ")[0]))/131)
    t1_temp.append(float(a[7].strip().split(" ")[0]))
    t1_temp.append(float(a[8].strip().split(" ")[0]))
    t1_temp.append(float(a[9].strip().split(" ")[0]))
    t2_temp.append(float(a[10].strip().split(" ")[0]))
    t2_temp.append(float(a[11].strip().split(" ")[0]))
    t2_temp.append(float(a[12].strip().split(" ")[0]))
    t2_temp.append((float(a[13].strip().split(" ")[0]))/131)
    t2_temp.append(-(float(a[14].strip().split(" ")[0]))/131)
    t2_temp.append((float(a[15].strip().split(" ")[0]))/131)
    t2_temp.append(float(a[16].strip().split(" ")[0]))
    t2_temp.append(float(a[17].strip().split(" ")[0]))
    t2_temp.append(float(a[18].strip().split(" ")[0]))
    k1_temp.append(float(a[19].strip().split(" ")[0]))
    k1_temp.append(float(a[20].strip().split(" ")[0]))
    k1_temp.append(float(a[21].strip().split(" ")[0]))
    k1_temp.append((float(a[22].strip().split(" ")[0]))/131)
    k1_temp.append(-(float(a[23].strip().split(" ")[0]))/131)
    k1_temp.append((float(a[24].strip().split(" ")[0]))/131)
    k1_temp.append(float(a[25].strip().split(" ")[0]))
    k1_temp.append(float(a[26].strip().split(" ")[0]))
    k1_temp.append(float(a[27].strip().split(" ")[0]))
    k2_temp.append(float(a[28].strip().split(" ")[0]))
    k2_temp.append(float(a[29].strip().split(" ")[0]))
    k2_temp.append(float(a[39].strip().split(" ")[0]))
    k2_temp.append((float(a[31].strip().split(" ")[0]))/131)
    k2_temp.append(-(float(a[32].strip().split(" ")[0]))/131)
    k2_temp.append((float(a[33].strip().split(" ")[0]))/131)
    k2_temp.append(float(a[34].strip().split(" ")[0]))
    k2_temp.append(float(a[35].strip().split(" ")[0]))
    k2_temp.append(float(a[36].strip().split(" ")[0]))
    w_temp.append(float(a[37].strip().split(" ")[0]))
    w_temp.append(float(a[38].strip().split(" ")[0]))
    w_temp.append(float(a[39].strip().split(" ")[0]))
    w_temp.append(float(a[40].strip().split(" ")[0]))
    w_temp.append(float(a[41].strip().split(" ")[0]))
    back_temp.append(float(a[42].strip().split(" ")[0]))
    back_temp.append(float(a[43].strip().split(" ")[0]))
    back_temp.append(float(a[44].strip().split(" ")[0]))
    back_temp.append(float(a[45].strip().split(" ")[0]))
    back_temp.append(float(a[46].strip().split(" ")[0]))
    time.append(float((a[46].strip().split(" "))[2][4:]))
    t1.append(t1_temp)
    t2.append(t2_temp)
    k1.append(k1_temp)
    k2.append(k2_temp)
    w.append(w_temp)
    back.append(back_temp)

In [80]:
time[0] = int(time[0])
for i in range(len(time)-1):
    time[i+1] = int(time[i+1]) + int(time[i])

In [81]:
time = np.array(time)
t1 = np.array(t1)
t2 = np.array(t2)
k1 = np.array(k1)
k2 = np.array(k2)
w = np.array(w)
back = np.array(back)

In [82]:
time = time/1000
time = time + 0.25

In [83]:
for i in range(len(time)):
    temp=[]
    accy = math.atan2(t1[i][0], t1[i][2])*180/PI + 90
    accx = math.atan2(t1[i][1],t1[i][2])*80/PI + 90
    dt=0.01
    t1_theta = 0.85*(t1_old_theta+np.array([t1[i][4],t1[i][3]])*dt)+0.15*np.array([accy,accx])
    t1_old_theta = t1_theta
    temp.append(t1_theta)
    accy = math.atan2(t2[i][0], t2[i][2])*180/PI + 90
    accx = math.atan2(t2[i][1],t2[i][2])*80/PI + 90
    dt=0.01
    t2_theta = 0.85*(t2_old_theta+np.array([t2[i][4],t2[i][3]])*dt)+0.15*np.array([accy,accx])
    t2_old_theta = t2_theta
    temp.append(t2_theta)
    accy = math.atan2(k1[i][0], k1[i][2])*180/PI + 90
    accx = math.atan2(k1[i][1],k1[i][2])*80/PI + 90
    dt=0.01
    k1_theta = 0.85*(k1_old_theta+np.array([k1[i][4],k1[i][3]])*dt)+0.15*np.array([accy,accx])
    k1_old_theta = k1_theta
    temp.append(k1_theta)
    accy = math.atan2(k2[i][0], k2[i][2])*180/PI + 90
    accx = math.atan2(k2[i][1],k2[i][2])*80/PI + 90
    dt=0.01
    k2_theta = 0.85*(k2_old_theta+np.array([k2[i][4],k2[i][3]])*dt)+0.15*np.array([accy,accx])
    k2_old_theta = k2_theta
    temp.append(k2_theta)
    pitch_roll.append(temp)
    
    

In [84]:
w

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
t1

array([[ -933.,   153.,  -286., ...,  4247.,  5107., -5649.],
       [ -933.,   153.,  -286., ...,  4247.,  5107., -5649.],
       [ -925.,   160.,  -273., ...,  4301.,  5161., -5667.],
       ...,
       [  -41.,   185.,  -956., ...,  4319.,  4211.,  -812.],
       [  -41.,   185.,  -956., ...,  4319.,  4211.,  -812.],
       [  -41.,   185.,  -956., ...,  4319.,  4211.,  -812.]])

In [86]:
pitch_roll

[[array([-2.5566038 , 23.62358688]),
  array([27.7114639 , 20.24235575]),
  array([-4.94541061, 23.77154347]),
  array([27.0000649 , 19.50006489])],
 [array([-4.72971704, 43.70363573]),
  array([51.26620822, 37.44835814]),
  array([-9.33788091, 44.05309836]),
  array([49.95012007, 36.07512005])],
 [array([-6.48712608, 60.62317441]),
  array([71.28774088, 52.07346017]),
  array([-13.07148067,  61.29242001]),
  array([69.45766696, 50.16391694])],
 [array([-7.98092376, 75.00478229]),
  array([88.30604365, 64.50479689]),
  array([-15.87655598,  75.89455934]),
  array([86.03908181, 62.13939429])],
 [array([-9.2506518 , 87.22914899]),
  array([102.75831396,  75.04163015]),
  array([-18.26086998,  88.30637778]),
  array([100.13328444,  72.31855004])],
 [array([-10.32992062,  97.61986068]),
  array([115.07337191,  84.04708994]),
  array([-20.28753689,  98.85642344]),
  array([112.11335668,  80.97083242])],
 [array([-11.24729913, 106.45196562]),
  array([125.54117117,  91.70173076]),
  array([-

In [87]:
a ="dataBack.txt"
d = open(a,"a+")

for i in range(len(time)):
    d.write(str(time[i]) + "  ")
    #for t1
    for x in pitch_roll[i][0]:
        d.write(str(x) + "  ")
    d.write(str(t1[i][3]) + "  ")
    d.write(str(t1[i][4]) + "  ")
    d.write(str(t1[i][5]) + "  ")
         
    for x in pitch_roll[i][1]:
         d.write(str(x) + "  ")
    d.write(str(t2[i][3]) + "  ")
    d.write(str(t2[i][4]) + "  ")
    d.write(str(t2[i][5]) + "  ")
            
    for x in pitch_roll[i][2]:
        d.write(str(x) + "  ")
    d.write(str(k1[i][3]) + "  ")
    d.write(str(k1[i][4]) + "  ")
    d.write(str(k1[i][5]) + "  ")
           
    for x in pitch_roll[i][3]:
        d.write(str(x) + "  ")
    d.write(str(k2[i][3]) + "  ")
    d.write(str(k2[i][4]) + "  ")
    d.write(str(k2[i][5]) + "  ")
            
    for x in w[i]:
        d.write(str(x) + "  ")
    for x in back[i]:
        d.write(str(x) + "  ")
    d.write("\n")
d.close()